src/config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin

from osmaxx.excerptexport.urls import excerpt_export_urlpatterns
from osmaxx.core.urls import pages_patterns
from osmaxx.profile.urls import profile_patterns

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("version/", include("osmaxx.version.urls", namespace="version")),
        # browsable REST API
        path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
        path(
            "api/",
            include(
                "osmaxx.excerptexport.rest_api.urls", namespace="excerptexport_api"
            ),
        ),
        path("pages/", include(pages_patterns)),
        path("profile/", include(profile_patterns)),
        path("", include(excerpt_export_urlpatterns)),
        path("", include("social_django.urls", namespace="social")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/osmaxx/excerptexport/rest_api/urls.py
from django.urls import path

from . import views

app_name = "osmaxx.excerptexport.rest_api"

urlpatterns = [
    path("bounding_geometry_from_excerpt/<int:pk>/", views.excerpt_detail),
    path("exports/<int:pk>/", views.export_detail, name="export-detail"),
    path("estimated_file_size/", views.estimated_file_size),
    path("format_size_estimation/", views.format_size_estimation),
]

src/osmaxx/excerptexport/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from osmaxx.excerptexport.views import (
    delete_excerpt,
    export_list,
    export_detail,
    manage_own_excerpts,
    order_new_excerpt,
    order_existing_excerpt,
)

app_name = "osmaxx.excerptexport"

_urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="excerptexport/templates/index.html"),
        name="index",
    ),
    path("exports/", export_list, name="export_list"),
    path("exports/<slug:id>/", export_detail, name="export_detail"),
    path("orders/new/new_excerpt/", order_new_excerpt, name="order_new_excerpt"),
    path(
        "orders/new/existing_excerpt/",
        order_existing_excerpt,
        name="order_existing_excerpt",
    ),
    path(
        "excerpts/<slug:pk>/delete/",
        delete_excerpt,
        name="delete_excerpt",
    ),
    path("excerpts/", manage_own_excerpts, name="manage_own_excerpts"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="osmaxx/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="osmaxx/logout.html"),
        name="logout",
    ),
]

excerpt_export_urlpatterns = (
    _urlpatterns,
    "excerptexport",
)
urlpatterns = [path("", include(excerpt_export_urlpatterns))]

src/osmaxx/excerptexport/forms/excerpt_form.py
import json

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field, Submit
from django import forms
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from osmaxx.excerptexport.models import Excerpt, ExtractionOrder
from osmaxx.utils.dict_helpers import select_keys
from .order_options_mixin import OrderOptionsMixin


class ExcerptForm(OrderOptionsMixin, forms.ModelForm):
    name = forms.CharField(
        label=_("Name"),
        required=True,
        widget=forms.TextInput(attrs={"required": "required"}),
    )
    bounding_geometry = forms.CharField(
        label=_("Bounding Geometry (GeoJSON)"),
        required=True,
        widget=forms.Textarea(attrs={"rows": "10"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        self.helper.form_id = "newExcerptForm"
        self.helper.form_method = "post"
        self.helper.form_action = reverse("excerptexport:order_new_excerpt")

        self.helper.layout = Layout(
            Fieldset(
                _("Excerpt"),
                Field("name"),
                Field("bounding_geometry"),
            ),
            OrderOptionsMixin(self).form_layout(),
            Submit("submit", "Export (will take more than 30 minutes)"),
        )

    def clean(self):
        clean = super().clean()
        if "bounding_geometry" in self._errors:
            # need to add the hidden field validation error to a visible dom
            self.add_error(None, _("Area Invalid or none selected."))
        return clean

    def clean_bounding_geometry(self):
        allowed_types = ["Polygon", "Multipolygon"]
        data = self.cleaned_data["bounding_geometry"]
        data_dict = json.loads(data)
        if data_dict.get("type") not in allowed_types:
            raise ValidationError(
                _("Only {} are allowed as input.").format(allowed_types)
            )
        if data_dict.get("type") == "Polygon":
            data_dict["coordinates"] = [data_dict.get("coordinates")]
            data_dict["type"] = "Multipolygon"
        return json.dumps(data_dict)

    class Meta:
        model = Excerpt
        fields = ["name", "bounding_geometry"]

    def save(self, user, request):
        extraction_order = ExtractionOrder(orderer=user)
        extraction_order.coordinate_reference_system = self.cleaned_data[
            "coordinate_reference_system"
        ]
        extraction_order.extraction_formats = self.cleaned_data["formats"]
        extraction_order.detail_level = self.cleaned_data["detail_level"]

        excerpt_dict = select_keys(self.cleaned_data, ["name", "bounding_geometry"])
        excerpt = Excerpt(is_active=True, owner=user, **excerpt_dict)
        excerpt.save()
        # cheap way to later on call the website from the worker to
        # invoke the middleware that sends emails, in order not to have to rely
        # on people using the site
        callback_uri = request.build_absolute_uri("/")
        extraction_order.invoke_update_url = callback_uri
        extraction_order.excerpt = excerpt
        extraction_order.save()
        return extraction_order

src/osmaxx/excerptexport/rest_api/views.py
import json
from osmaxx.conversion import output_format
from osmaxx.conversion.size_estimator import size_estimation_for_format

from django.http import HttpResponse
from rest_framework import viewsets
from rest_framework_extensions.etag.mixins import ETAGMixin

from pbf_file_size_estimation.estimate_size import estimate_size_of_extent
from osmaxx.contrib.auth.frontend_permissions import (
    AuthenticatedAndAccessPermission,
    HasExcerptAccessPermission,
    HasExportAccessPermission,
)
from osmaxx.excerptexport.models import Excerpt, Export
from osmaxx.excerptexport.rest_api.serializers import (
    ExcerptGeometrySerializer,
    ExportSerializer,
)


class ExcerptViewSet(
    ETAGMixin, viewsets.mixins.RetrieveModelMixin, viewsets.GenericViewSet
):
    permission_classes = (
        HasExcerptAccessPermission,
        AuthenticatedAndAccessPermission,
    )
    queryset = Excerpt.objects.all()
    serializer_class = ExcerptGeometrySerializer


excerpt_detail = ExcerptViewSet.as_view(
    {"get": "retrieve"}
)


class ExportViewSet(viewsets.mixins.DestroyModelMixin, viewsets.GenericViewSet):
    permission_classes = (
        HasExportAccessPermission,
        AuthenticatedAndAccessPermission,
    )
    queryset = Export.objects.all()
    serializer_class = ExportSerializer


export_detail = ExportViewSet.as_view(
    {"delete": "destroy"}
)


def estimated_file_size(request):
    from pbf_file_size_estimation.app_settings import (
        PBF_FILE_SIZE_ESTIMATION_CSV_FILE_PATH,
    )

    size_csv = PBF_FILE_SIZE_ESTIMATION_CSV_FILE_PATH
    bbox = {
        bound: float(request.GET[bound]) for bound in ["north", "east", "west", "south"]
    }
    size = estimate_size_of_extent(
        size_csv,
        west=bbox["west"],
        south=bbox["south"],
        east=bbox["east"],
        north=bbox["north"],
    )
    response_content = json.dumps({"estimated_file_size_in_bytes": size})
    return HttpResponse(response_content, content_type="application/json")


def format_size_estimation(request):
    detail_level = int(request.GET["detail_level"])
    estimated_pbf_size = float(request.GET["estimated_pbf_file_size_in_bytes"])
    result = {
        format_name: size_estimation_for_format(
            format_name, detail_level, estimated_pbf_size
        )
        for format_name in output_format.DEFINITIONS
    }
    response_content = json.dumps(result)
    return HttpResponse(response_content, content_type="application/json")

src/osmaxx/excerptexport/views.py
import logging
from collections import OrderedDict

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils.datastructures import OrderedSet
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView, GenericViewError
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin, DeleteView
from django.views.generic.list import ListView

from osmaxx.contrib.auth.frontend_permissions import EmailRequiredMixin
from osmaxx.conversion import status
from osmaxx.excerptexport.forms import ExcerptForm, ExistingForm
from osmaxx.excerptexport.models import Excerpt
from osmaxx.excerptexport.models import ExtractionOrder
from .models import Export

from osmaxx.conversion.tasks import start_conversion

logger = logging.getLogger(__name__)


class OrderFormViewMixin(FormMixin):
    def form_valid(self, form):
        extraction_order = form.save(self.request.user, request=self.request)
        task_id = start_conversion.delay(extraction_order.id)
        # mostly for debugging purposes
        extraction_order.assigned_task_id = str(task_id)
        messages.info(
            self.request,
            _(
                "Queued extraction order {id}. The conversion process will start soon."
            ).format(id=extraction_order.id),
        )
        return HttpResponseRedirect(reverse("excerptexport:export_list"))


class OrderNewExcerptView(
    LoginRequiredMixin, EmailRequiredMixin, OrderFormViewMixin, FormView
):
    template_name = "excerptexport/templates/order_new_excerpt.html"
    form_class = ExcerptForm


order_new_excerpt = OrderNewExcerptView.as_view()


class OrderExistingExcerptView(
    LoginRequiredMixin, EmailRequiredMixin, OrderFormViewMixin, FormView
):
    template_name = "excerptexport/templates/order_existing_excerpt.html"
    form_class = ExistingForm

    def get_form_class(self):
        return super().get_form_class().get_dynamic_form_class(self.request.user)


order_existing_excerpt = OrderExistingExcerptView.as_view()


class OwnershipRequiredMixin(SingleObjectMixin):
    owner = "owner"

    def get_object(self, queryset=None):
        o = super().get_object(queryset)
        if getattr(o, self.owner) != self.request.user:
            raise PermissionDenied
        return o


class ExportsListMixin:
    _filterable_statuses = frozenset({status.FINISHED, status.FAILED})

    @property
    def excerpt_ids(self):
        if not hasattr(self, "_excerpt_ids"):
            self._excerpt_ids = list(
                OrderedSet(
                    self.get_user_exports().values_list(
                        "extraction_order__excerpt", flat=True
                    )
                )
            )
        return self._excerpt_ids

    @property
    def status_choices(self):
        return [
            choice
            for choice in status.CHOICES
            if choice[0] in self._filterable_statuses
        ]

    def get_user_exports(self):
        return self._filter_exports(
            Export.objects.filter(extraction_order__orderer=self.request.user).defer(
                "extraction_order__excerpt__bounding_geometry"
            )
        ).order_by("-updated_at", "-finished_at")

    def _filter_exports(self, query):
        status_filter = self.request.GET.get("status", None)
        if status_filter in self._filterable_statuses:
            return query.filter(status=status_filter)
        return query

    def _get_extra_context_data(self):
        return dict(
            status_choices=self.status_choices,
            status_filter=self.request.GET.get("status", None),
        )


class ExportsListView(LoginRequiredMixin, ExportsListMixin, ListView):
    template_name = "excerptexport/export_list.html"
    context_object_name = "excerpts"
    model = Excerpt
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(self._get_extra_context_data())
        context_data["excerpt_list_with_exports"] = OrderedDict(
            (excerpt, self._get_exports_for_excerpt(excerpt))
            for excerpt in context_data[self.context_object_name]
        )
        return context_data

    def get_queryset(self):
        return sorted(
            super()
            .get_queryset()
            .filter(pk__in=self.excerpt_ids)
            .defer("bounding_geometry"),
            key=lambda x: self.excerpt_ids.index(x.pk),
        )

    def _get_exports_for_excerpt(self, excerpt):
        return (
            self.get_user_exports()
            .filter(extraction_order__excerpt=excerpt)
            .select_related(
                "extraction_order", "extraction_order__excerpt", "output_file"
            )
            .defer("extraction_order__excerpt__bounding_geometry")
        )


export_list = ExportsListView.as_view()


class ExportsDetailView(LoginRequiredMixin, ExportsListMixin, ListView):
    template_name = "excerptexport/export_detail.html"
    context_object_name = "exports"
    model = Export
    pk_url_kwarg = "id"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(self._get_extra_context_data())
        return context_data

    def get_queryset(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is None:
            raise AttributeError("ExportsDetailView must be called with an Excerpt pk.")
        queryset = (
            self.get_user_exports()
            .select_related(
                "extraction_order", "extraction_order__excerpt", "output_file"
            )
            .filter(extraction_order__excerpt__pk=pk)
        )
        return queryset


export_detail = ExportsDetailView.as_view()


class ExcerptManageListView(ListView):
    model = Excerpt
    context_object_name = "excerpts"
    template_name = "excerptexport/excerpt_manage_list.html"

    def get_queryset(self):
        user = self.request.user
        return (
            super()
            .get_queryset()
            .filter(owner=user, is_public=False, extraction_orders__orderer=user)
            .distinct()
        )


manage_own_excerpts = ExcerptManageListView.as_view()


class DeleteExcerptView(DeleteView):
    model = Excerpt
    context_object_name = "excerpt"
    template_name = "excerptexport/excerpt_confirm_delete.html"

    def get_success_url(self):
        return reverse("excerptexport:manage_own_excerpts")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        excerpt = context_data[self.context_object_name]
        context_data["exports"] = Export.objects.filter(
            extraction_order__excerpt=excerpt
        )
        return context_data

    def form_valid(self, request, *args, **kwargs):
        excerpt = self.get_object()
        user = self.request.user
        if user != excerpt.owner:
            raise GenericViewError("User doesn't match the excerpt's owner.")
        if excerpt.is_public:
            raise GenericViewError("No self-defined public excerpts can be deleted.")
        if ExtractionOrder.objects.exclude(orderer=user).count() > 0:
            raise GenericViewError("Others' exports reference this excerpt.")
        if excerpt.has_running_exports:
            logger.error("Deletion not allowed during an active extraction.")
            messages.error(
                self.request,
                _(
                    "Exports are currently running for this excerpt."
                    " Please try deleting again, when these are finished."
                ),
            )
            return HttpResponseRedirect(self.get_success_url())

        return super().delete(request, *args, **kwargs)


delete_excerpt = DeleteExcerptView.as_view()

src/osmaxx/excerptexport/templates/excerptexport/base.html
{% extends 'osmaxx/base.html' %}
{% load static %}
{% block extracss %}
<link rel='stylesheet' type='text/css'
    href='{% static "excerptexport/libraries/jquery-ui-1.11.4/jquery-ui.min.css" %}' />
<link rel='stylesheet' type='text/css' href='{% static "excerptexport/css/resizable_select_box.css" %}' />
<link rel="stylesheet" type="text/css" href='{% static "excerptexport/libraries/leaflet/leaflet.css" %}' />
<link rel="stylesheet" type="text/css" href='{% static "excerptexport/css/excerptexport.css" %}' />
{% endblock %}

{% block main %}
<div class="container-row">
    <h2>Content</h2>
</div>
{% endblock %}

{% block scripts %}
{# JQuery UI Plugin needed for the resizable select box script #}
<script src='{% static "excerptexport/libraries/jquery-ui-1.11.4/jquery-ui.min.js" %}'></script>
{# resizable select box script #}
<script src='{% static "excerptexport/scripts/resizable_select_box.js" %}'></script>

{# Helpers #}
<script type="text/javascript" src="{% static 'excerptexport/scripts/helperFunctions.js' %}"></script>
{# cookie getter, as per Django docs: https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax #}
<script type="text/javascript" src='{% static "excerptexport/libraries/django/js.cookie-2.1.2.min.js" %}'></script>
<script type="text/javascript" src='{% static "excerptexport/scripts/add_delete_button_to_exports.js" %}'></script>

{# MAP SCRIPTS #}
<script src='{% static "excerptexport/libraries/leaflet/leaflet.js" %}'></script>
<script src='{% static "excerptexport/scripts/maps/LeafletSetup.js" %}'></script>

{# Leaflet plugins #}
<script src='{% static "excerptexport/libraries/Leaflet.Spin/spin.min.js" %}'></script>
<script src='{% static "excerptexport/libraries/Leaflet.Spin/leaflet.spin.js" %}'></script>
<script src='{% static "excerptexport/libraries/leaflet-ajax/leaflet.ajax.min.js" %}'></script>
<script src='{% static "excerptexport/scripts/estimate_size.js" %}'></script>
{% endblock %}

src/osmaxx/excerptexport/templates/excerptexport/excerpt_confirm_delete.html
{% extends 'excerptexport/base.html' %}{% load i18n capture_as static %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="active">{% trans 'Excerpt Deletion' %}</li>
{% endblock %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 last">
                <h2>{% trans 'Delete excerpt and dependent data' %}</h2>
                <h3>{{ excerpt.name }}</h3>
                <p>This will also delete the following Exports:</p>
                <ul>
                    {% for export in exports %}
                        <li>
                            {% include 'excerptexport/partials/export_detail_string.html' %}
                        </li>
                    {% empty %}
                        <li>{% trans 'No Exports attached.' %}</li>
                    {% endfor %}
                </ul>
                <div class="col-xs-6">
                    <a href="{% url 'excerptexport:manage_own_excerpts' %}" class="btn btn-success">No</a>
                </div>
                <div class="col-xs-6 last">
                    <form href="{% url 'excerptexport:delete_excerpt' pk=excerpt.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Yes" />
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/osmaxx/excerptexport/templates/excerptexport/excerpt_manage_list.html
{% extends 'excerptexport/base.html' %}{% load i18n static export_count_for_user %}
{% block breadcrumb %}
    {{ block.super }}
    / <a href="{% url 'excerptexport:order_existing_excerpt' %}">Existing excerpt Export</a> /
    <li class="active">{% trans 'Excerpt List' %}</li>
{% endblock %}


{% block main %}
    <div class="container-row content">
        <div class="col-lg-12">
            {% for excerpt in excerpts %}
                <div class="col-md-4">
                    {% export_count_for_user user=request.user excerpt=excerpt as export_count %}
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3>{{ excerpt.name }}</h3>
                        </div>
                        <div class="panel-body">
                            {% blocktrans %}Contains {{ export_count }} export(s).{% endblocktrans %}<br />
                            <a href="{% url 'excerptexport:export_detail' id=excerpt.id %}">{% trans 'See your exports.' %}</a>
                        </div>
                        <div class="panel-footer">
                            {% if excerpt.has_running_exports %}
                                {% trans 'You have running exports for this excerpt. It is not possible to delete during extraction.' %}
                            {% else %}
                                <a class="btn btn-danger" href="{% url 'excerptexport:delete_excerpt' pk=excerpt.id %}">{% trans 'Delete this excerpt and all attached data' %}</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <h2>{% trans 'You have no personal, non-public excerpts.' %}</h2>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/osmaxx/excerptexport/templates/excerptexport/export_detail.html
{% extends 'excerptexport/base.html' %}{% load i18n capture_as email_bodies static %}
{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'excerptexport:export_list' %}">{% trans 'My Exports' %}</a></li>
    <li class="active">{% trans 'Exports' %}{% if exports %}{% with excerpt=exports.0.extraction_order.excerpt %} {{ excerpt.name }}{% endwith %}{% endif %}</li>
{% endblock %}


{% block main %}
    <div class="container-row content">
        <div class="col-lg-10">
            {% if exports %}
                {% with excerpt=exports.0.extraction_order.excerpt %}
                    <div class="row">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">{{ excerpt.name }}</h3>
                            </div>
                            <div class="panel-body">
                                <div class="col-lg-6">
                                    {% for export in exports %}
                                        {% include 'excerptexport/partials/export_display.html' %}
                                    {% endfor %}
                                </div>
                                <div class="col-lg-6">
                                    {% with min_height=70 %}
                                        {% include 'excerptexport/partials/minimap.html' %}
                                    {% endwith %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% else %}
                {% comment %}
                    This will also be shown when the user has no access to this export data,
                    i.e. trying to access somebody else's data. Be friendly :-)
                {% endcomment %}
                {% include 'excerptexport/partials/no_exports_message.html' %}
            {% endif %}
        </div>
        <div class="col-lg-2">
            <p style="font-size: larger">{% include 'excerptexport/partials/refresh_export_message.html' %}</p>
            {% include 'excerptexport/partials/export_sidebar.html' %}
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src='{% static "excerptexport/scripts/maps/excerpt_viewer.js" %}'></script>
    <script src='{% static "excerptexport/scripts/maps/minimap.js" %}'></script>
{% endblock %}

src/osmaxx/excerptexport/templates/excerptexport/export_list.html
{% extends 'excerptexport/base.html' %}{% load i18n capture_as email_bodies static %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="active">{% trans 'My Exports' %}</li>
{% endblock %}


{% block main %}
    <div class="container-row content">
        <div class="row">
            <div class="col-lg-10">
                <h2>{% trans 'My Exports' %}</h2>
            </div>
        </div>
        <div class="col-lg-10">
            {% for excerpt, exports in excerpt_list_with_exports.items %}
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ excerpt.name }}</h3>
                        </div>
                        <div class="panel-body">
                            <div class="col-lg-6">
                                {% for export in exports|slice:":5" %}
                                    {% include 'excerptexport/partials/export_display.html' %}
                                {% endfor %}
                                {% if exports|length > 5 %}<a href="{% url 'excerptexport:export_detail' id=excerpt.id %}">{% trans 'see all your exports of this excerpt.' %} ({{ exports|length }})</a>{% endif %}
                            </div>
                            <div class="col-lg-6">
                                {% include 'excerptexport/partials/minimap.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                {% include 'excerptexport/partials/no_exports_message.html' %}
            {% endfor %}
        </div>
        <div class="col-lg-2">
            <p style="font-size: larger;">{% include 'excerptexport/partials/refresh_export_message.html' %}</p>
            {% include 'excerptexport/partials/export_sidebar.html' %}
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script src='{% static "excerptexport/scripts/maps/excerpt_viewer.js" %}'></script>
    <script src='{% static "excerptexport/scripts/maps/minimap.js" %}'></script>
{% endblock %}